### ISSUE TITLE
Broken after Moose 2.110 

### ISSUE THREAD

**Issue by kentfredric** [doy/moosex-aliases#5]
private method `_inline_throw_error` no longer exists:

http://www.cpantesters.org/cpan/report/e437f9c6-39fa-11e3-aff3-312ff34aa4a3 

Diffing moose: https://metacpan.org/diff/release/ETHER/Moose-2.1005/ETHER/Moose-2.1102-TRIAL 

Suggests that `_inline_throw_exception` is the replacement.

**Comment by doy** [comment]
As far as I'm aware, this was fixed in Moose in 2.1106. Let me know if you still have issues.
